[build]
command = "npm start" # 使用npm start作为启动命令
publish = "public" # 项目构建后的输出目录
functions = "functions" # 如果您有服务器less功能，指定函数的目录

[build.environment]
WEB_USERNAME = "admin" # 配置环境变量
WEB_PASSWORD = "password"
PROJECT_DOMAIN = "incomparable-puffpuff-5ca434" # 替换为您的项目域名

[functions]
node_bundler = "npm" # 使用npm作为函数的包管理器
